export enum AboutUsPageText {
  Title = 'About Us',
  SubtitleTeam = 'Our team:',
  SubtitleDescription = 'Description:',
  OurTeamLider = 'our team leader:',
  ExTeamLider = 'ex-team leader:',
  OurTeamMember = 'team member:',
  Marat = 'Marat Bondarenko - hard worker and a team leader. Contributed to the common cause - 30633/37260 lines code.',
  Alex = 'Aliaksandr Klintsevich - ex-team leader. Contributed to the common cause - 882/37260 lines code.',
  Mikalai = 'Mikalai Aliakhnovich - Contributed to the common cause - 5744/37260 lines code.',
  MikalaiBio = 'I’m 39 years old. I’m originally from Belarus and live in a small town near the capital. I have worked in the building industry all my life, including in senior positions. Currently I work in project management for construction at the developer’s company. I have an architecture degree. I finished Belarusian National Technical University.',
  AlexBio = 'Alas, he left us on the Sprint 3.',
  Description = 'This is a student frontend project for creating an online store based on commercetools. This project was created as part of the RS School JavaScript/Front-end 2023Q1 course. Commercetools is a flexible and powerful e-commerce platform that allows you to create modern online stores using the latest technologies.',
  BuiltWith = 'Built with:',
  UsedTools = 'Used tools:',
  BuiltWithTextLine1 = 'HTML: for structuring the content of the web pages',
  BuiltWithTextLine2 = 'CSS (with SASS preprocessor): for styling the web pages and making them visually appealing',
  BuiltWithTextLine3 = 'TypeScript (TS): for generating the SPA and adding interactivity to the web pages, handling user interactions, and managing the application state',
  UsedToolsLine1 = 'VS Code, Git, GitHub, Github Projects, Commercetools, Figma, Netlify, Webpack, ESLint, Husky, npm',
  GithubMarat = 'nowaylifer',
  GithubAliaksandr = 'spacepocket1985',
  GithubMikalai = 'nickoff',
}

export enum AboutUsPageLink {
  Rsschool = 'https://rs.school',
  GithubMarat = 'https://github.com/nowaylifer',
  GithubAliaksandr = 'https://github.com/spacepocket1985',
  GithubMikalai = 'https://github.com/nickoff',
}
